pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'gabiadaf07/backup:latest'
        DOCKER_CREDENTIALS_ID = 'credentiale-dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    docker run --rm \
                    -v "/var/jenkins_home/workspace/CICD MonitoringPlatform/monitoring-platform:/app" \
                    -w /app \
                    python:3.12-slim \
                    bash -c "pip install --no-cache-dir flake8 && flake8 /app/scripts/backup.py"
                '''
            }
        }





        stage('Unit Tests') {
            steps {
                sh 'pytest tests/'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f docker/backup/Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml up -d'
            }
        }
    }
}
