pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'gabiadaf07/backup:latest'
        DOCKER_CREDENTIALS_ID = 'credentiale-dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    echo "Workspace: $WORKSPACE"
                    docker run --rm \
                        -v "$WORKSPACE:/app" \
                        -w /app \
                        python:3.12-slim \
                        bash -c "apt-get update -qq && apt-get install -y findutils >/dev/null && pip install --no-cache-dir flake8 && ls -R && flake8 $(find . -name '*.py')"
                '''
            }
        }











        stage('Unit Tests') {
            steps {
                sh 'pytest tests/'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f docker/backup/Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml up -d'
            }
        }
    }
}
